name: Java CI
on:
    # Trigger analysis when pushing in master or pull requests, and when creating
    # a pull request.
    push:
        branches:
            - main
            - feature/*
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Cache SonarCloud packages
              uses: actions/cache@v1
              with:
                  path: ~/.sonar/cache
                  key: ${{ runner.os }}-sonar
                  restore-keys: ${{ runner.os }}-sonar

            - name: Build and analyze
              run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
              env:
                  # Needed to get some information about the pull request, if any
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Docker Login
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{secrets.DOCKER_LOGIN}}
                  password: ${{secrets.DOCKER_TOKEN}}
